name: note_app
description: This  CRUD Note Application for repeat local database Hive


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-168.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  date_format: any

  # for local database
  path_provider: any
  hive: any
  hive_flutter: any
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  hive_generator: any
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

